
name: Maven Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        type: string

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: us-west-2

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: "${{ secrets.ACTIONS_SECRET_ROLE_NAME }}"
          role-session-name: mavenreleasesession
          aws-region: ${{ env.AWS_REGION }}

      - name: build mvn
        run: mvn clean install -q -Dlog4j2.level=WARN -Dlog4j.configurationFile=log4j2-quiet.xml --no-transfer-progress

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: Release v${{ github.event.inputs.release_version }}
          generate_release_notes: true
          files: |
            sdk/target/aws-durable-execution-sdk-java-${{ github.event.inputs.release_version }}.jar
            sdk-testing/target/aws-durable-execution-sdk-java-testing-${{ github.event.inputs.release_version }}.jar
